CREATE TABLE municipalities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code INT NOT NULL UNIQUE COMMENT '全国地方公共団体コード',
    name VARCHAR(255) NOT NULL COMMENT '地方公共団体名',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'レコード作成日時',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'レコード更新日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='地方公共団体マスタ';
